=== CESNET/eduroam-monitor/eduroamdb/edudb/xsd/ver26032008/institution_usage.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="institution_usages">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="institution_usage">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="usage">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="local_sn" type="xs:int"/>
										<xs:element name="national_sn" type="xs:int"/>
										<xs:element name="international_sn" type="xs:int"/>
									</xs:sequence>
									<xs:attribute name="date" type="xs:date" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="inst_realm" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== CESNET/eduroam-monitor/eduroamdb/edudb/xml-example/ver17042008/institution_usage.xml
<?xml version="1.0" encoding="UTF-8"?>
<institution_usages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="institution_usage.xsd">
	<institution_usage inst_realm="inst_realm0">
		<usage date="2006-05-03"> </usage>
		<usage date="2006-05-04">
			<local_sn>2147483647</local_sn>
			<national_sn>2147483647</national_sn>
		</usage>
		<usage date="2006-05-05">
			<local_sn>2147483647</local_sn>
			<national_sn>2147483647</national_sn>
			<international_sn>2147483647</international_sn>
		</usage>
	</institution_usage>
	<institution_usage inst_realm="inst_realm1">
		<usage date="2006-05-04">
			<local_sn>2147483647</local_sn>
			<national_sn>2147483647</national_sn>
			<international_sn>2147483647</international_sn>
		</usage>
	</institution_usage>
	<institution_usage inst_realm="inst_realm2">
		<usage date="2006-05-04">
			<international_sn>2147483647</international_sn>
		</usage>
		<usage date="2006-05-04">
			<local_sn>2147483647</local_sn>
			<national_sn>2147483647</national_sn>
			<international_sn>2147483647</international_sn>
		</usage>
		<usage date="2006-05-04">
			<local_sn>2147483647</local_sn>
			<national_sn>2147483647</national_sn>
			<international_sn>2147483647</international_sn>
		</usage>
	</institution_usage>
</institution_usages>
