=== CESNET/eduroam-monitor/eduroamdb/edudb/xsd/ver26032008/realm_data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="realm_data_root">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="realm_data">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="country" type="xs:string"/>
							<xs:element name="number_IdP" type="xs:int"/>
							<xs:element name="number_SP" type="xs:int"/>
							<xs:element name="number_SPIdP" type="xs:int"/>
							<xs:element name="number_inst" type="xs:int" minOccurs="0"/>
							<xs:element name="number_user" type="xs:int" minOccurs="0"/>
							<xs:element name="number_id" type="xs:int" minOccurs="0"/>
							<xs:element name="ts" type="xs:dateTime"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== CESNET/eduroam-monitor/eduroamdb/edudb/xml-example/ver26032008/realm_data.xml
<?xml version="1.0" encoding="UTF-8"?>
<realm_data_root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="realm_data.xsd">
	<realm_data>
		<country>country0</country>
		<number_IdP>2147483647</number_IdP>
		<number_SP>2147483647</number_SP>
		<number_SPIdP>2147483647</number_SPIdP>
		<ts>2006-05-04T18:13:51.0Z</ts>
	</realm_data>
	<realm_data>
		<country>country1</country>
		<number_IdP>2147483647</number_IdP>
		<number_SP>2147483647</number_SP>
		<number_SPIdP>2147483647</number_SPIdP>
		<ts>2006-05-04T18:13:51.0Z</ts>
	</realm_data>
	<realm_data>
		<country>country2</country>
		<number_IdP>2147483647</number_IdP>
		<number_SP>2147483647</number_SP>
		<number_SPIdP>2147483647</number_SPIdP>
		<ts>2006-05-04T18:13:51.0Z</ts>
	</realm_data>
</realm_data_root>
