=== CESNET/eduroam-monitor/eduroamdb/edudb/xsd/ver26032008/realm.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="eduroam_realm_stype">
		<xs:restriction base="xs:int">
			<xs:enumeration value="0">
				<xs:annotation>
					<xs:documentation>FLRS</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>(E)TLRS</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>

	</xs:simpleType>

	<xs:element name="realms">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="realm">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="country" type="xs:string"/>
							<xs:element name="stype" type="eduroam_realm_stype"/>
							<xs:element name="org_name" type="xs:string"/>
							<xs:element name="address_street" type="xs:string"/>
							<xs:element name="address_city" type="xs:string"/>
							<xs:element name="contact_name" type="xs:string"/>
							<xs:element name="contact_email" type="xs:string"/>
							<xs:element name="contact_phone" type="xs:string"/>
							<xs:element name="info_URL" type="xs:anyURI"/>
							<xs:element name="policy_URL" type="xs:anyURI"/>
							<xs:element name="ts" type="xs:dateTime">
								<xs:annotation>
									<xs:documentation> Format: 2008-02-29T12:00:00 </xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== CESNET/eduroam-monitor/eduroamdb/edudb/xml-example/ver26032008/realm.xml
<?xml version="1.0" encoding="UTF-8"?>
<realms xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="realm.xsd">
	<realm>
		<country>country0</country>
		<stype>0</stype>
		<org_name>org_name0</org_name>
		<address_street>address_street0</address_street>
		<address_city>address_city0</address_city>
		<contact_name>contact_name0</contact_name>
		<contact_email>contact_email0</contact_email>
		<contact_phone>contact_phone0</contact_phone>
		<info_URL>http://www.oxygenxml.com/</info_URL>
		<policy_URL>http://www.oxygenxml.com/</policy_URL>
		<ts>2006-05-04T18:13:51.0Z</ts>
	</realm>
</realms>
