=== CESNET/eduroam-monitor/eduroamdb/edudb/xsd/ver26032008/service_loc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="service_locs">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="service_loc">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="inst_realm" type="xs:string"/>
							<xs:element name="longitude" type="xs:string"/>
							<xs:element name="latitude" type="xs:string"/>
							<xs:element name="address_street" type="xs:string"/>
							<xs:element name="address_city" type="xs:string"/>
							<xs:element name="contact_name" type="xs:string"/>
							<xs:element name="contact_email" type="xs:string"/>
							<xs:element name="contact_phone" type="xs:string"/>
							<xs:element name="SSID" type="xs:string"/>
							<xs:element name="enc_level" type="xs:string"/>
							<xs:element name="port_restrict" type="xs:boolean" default="0"/>
							<xs:element name="transp_proxy" type="xs:boolean" default="0" minOccurs="0"/>
							<xs:element name="IPv6" type="xs:boolean" default="0" minOccurs="0"/>
							<xs:element name="NAT" type="xs:boolean" default="0" minOccurs="0"/>
							<xs:element name="AP_no" type="xs:int" minOccurs="0"/>
							<xs:element name="wired" type="xs:boolean" default="0" minOccurs="0"/>
							<xs:element name="info_URL" type="xs:anyURI" minOccurs="0"/>
							<xs:element name="ts" type="xs:dateTime">
								<xs:annotation>
									<xs:documentation> Format: 2008-02-29T12:00:00 </xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== CESNET/eduroam-monitor/eduroamdb/edudb/xml-example/ver26032008/service_loc.xml
<?xml version="1.0" encoding="UTF-8"?>
<service_locs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="service_loc.xsd">
	<service_loc>
		<inst_realm>inst_realm0</inst_realm>
		<longitude>longitude0</longitude>
		<latitude>latitude0</latitude>
		<address_street>address_street0</address_street>
		<address_city>address_city0</address_city>
		<contact_name>contact_name0</contact_name>
		<contact_email>contact_email0</contact_email>
		<contact_phone>contact_phone0</contact_phone>
		<SSID>SSID0</SSID>
		<enc_level>enc_level0</enc_level>
		<port_restrict>false</port_restrict>
		<ts>2006-05-04T18:13:51.0Z</ts>
	</service_loc>
	<service_loc>
		<inst_realm>inst_realm1</inst_realm>
		<longitude>longitude1</longitude>
		<latitude>latitude1</latitude>
		<address_street>address_street1</address_street>
		<address_city>address_city1</address_city>
		<contact_name>contact_name1</contact_name>
		<contact_email>contact_email1</contact_email>
		<contact_phone>contact_phone1</contact_phone>
		<SSID>SSID1</SSID>
		<enc_level>enc_level1</enc_level>
		<port_restrict>false</port_restrict>
		<ts>2006-05-04T18:13:51.0Z</ts>
	</service_loc>
	<service_loc>
		<inst_realm>inst_realm2</inst_realm>
		<longitude>longitude2</longitude>
		<latitude>latitude2</latitude>
		<address_street>address_street2</address_street>
		<address_city>address_city2</address_city>
		<contact_name>contact_name2</contact_name>
		<contact_email>contact_email2</contact_email>
		<contact_phone>contact_phone2</contact_phone>
		<SSID>SSID2</SSID>
		<enc_level>enc_level2</enc_level>
		<port_restrict>false</port_restrict>
		<IPv6>false</IPv6>
		<NAT>false</NAT>
		<AP_no>3333</AP_no>
		<wired>false</wired>
		<info_URL>http://www.url.org/info</info_URL>
		<ts>2006-05-04T18:13:51.0Z</ts>
	</service_loc>
</service_locs>
