=== CESNET/eduroam-monitor/eduroamdb/edudb/xsd/ver17042008/realm.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="eduroam_realm_stype">
		<xs:restriction base="xs:int">
			<xs:enumeration value="0">
				<xs:annotation>
					<xs:documentation>FLRS</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>(E)TLRS</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>

	</xs:simpleType>

	<xs:element name="realms">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="realm">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="country" type="xs:string"/>
							<xs:element name="stype" type="eduroam_realm_stype"/>
							<xs:element name="org_name" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="lang" type="xs:string" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="address">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="street" type="xs:string"/>
										<xs:element name="city" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="contact" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name" type="xs:string"/>
										<xs:element name="email" type="xs:string"/>
										<xs:element name="phone" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="info_URL" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:anyURI">
											<xs:attribute name="lang" type="xs:string" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="policy_URL" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:anyURI">
											<xs:attribute name="lang" type="xs:string" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="ts" type="xs:dateTime">
								<xs:annotation>
									<xs:documentation> Format: 2008-02-29T12:00:00 </xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== CESNET/eduroam-monitor/eduroamdb/edudb/xml-example/ver17042008/realm.xml
<?xml version="1.0" encoding="UTF-8"?>
<realms xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="realm.xsd">
	<realm>
		<country>country0</country>
		<stype>0</stype>
		<org_name lang="en">org_name0</org_name>
		<address>
			<street>street0</street>
			<city>city0</city>
		</address>
		<contact>
			<name>name0</name>
			<email>email0</email>
			<phone>phone0</phone>
		</contact>
		<contact>
			<name>name1</name>
			<email>email1</email>
			<phone>phone1</phone>
		</contact>
		<contact>
			<name>name2</name>
			<email>email2</email>
			<phone>phone2</phone>
		</contact>
		<info_URL lang="en">http://www.eduroam.org/</info_URL>
		<policy_URL lang="en">http://www.eduroam.org/</policy_URL>
		<ts>2006-05-04T18:13:51.0Z</ts>
	</realm>
</realms>
