=== CESNET/eduroam-monitor/eduroamdb/edudb/xsd/ver17042008/realm_usage.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="realm_usages">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="realm_usage">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="usage">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="national_sn" type="xs:int" minOccurs="0"/>
										<xs:element name="international_sn" type="xs:int" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute name="date" use="required" type="xs:date"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="country" use="required" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== CESNET/eduroam-monitor/eduroamdb/edudb/xml-example/ver17042008/realm_usage.xml
<?xml version="1.0" encoding="UTF-8"?>
<realm_usages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="realm_usage.xsd">
	<realm_usage country="country0">
		<usage date="2006-05-04">
			<national_sn>2147483647</national_sn>
			<international_sn>2147483647</international_sn>
		</usage>
		<usage date="2006-05-04"> </usage>
	</realm_usage>
	<realm_usage country="country1">
		<usage date="2006-05-04">
			<national_sn>2147483647</national_sn>
		</usage>
		<usage date="2006-05-04">
			<national_sn>2147483647</national_sn>
			<international_sn>2147483647</international_sn>
		</usage>
		<usage date="2006-05-04">
			<international_sn>2147483647</international_sn>
		</usage>
	</realm_usage>
	<realm_usage country="country2">
		<usage date="2006-05-04">
			<national_sn>2147483647</national_sn>
			<international_sn>2147483647</international_sn>
		</usage>
	</realm_usage>
</realm_usages>
